name: build

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Update version
        uses: dmikey/package-json-version@v0.0.2
        with:
          version: ${{ github.ref_name }}
      - name: Install dependencies
        run: yarn install
      - name: Build on Linux
        run: yarn build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/${{ github.ref_name }}/LooofiX.AppImage
